42-student-council/website

app/app/settings.py
app/app/urls.py
app/db/models.py
app/db/views.py
app/front/app/components/NavBar.tsx
app/front/app/routes/_index.tsx
app/front/app/routes/issues.$id.tsx
app/front/app/routes/issues.$id.upvote.tsx
app/front/app/routes/issues._index.tsx
app/front/app/routes/issues.new.tsx

We now have an index page for issues, where users are able to view, upvote and comment issues anonymously.
Right now, it is possible to spam the upvote button - I will add a database model to store the user's hashed session in order to prevent that, but that is for a separate PR.

Issues index page

---

.github/docs/DOTENV.md
.github/docs/MAKEFILE.md
app/db/models.py
app/db/utils.py
app/db/views.py
app/front/app/routes/issues.$id.tsx
app/front/app/routes/issues.$id.upvote.tsx
app/front/app/routes/issues._index.tsx

* Each vote request now stores the hashed login of the user in order to prevent double votes/spam
* Added a popup message for invalid vote requests

Store hashed logins to prevent spam

---

.gitignore
app/app/urls.py
app/db/models.py
app/db/views.py
app/front/app/components/NavBar.tsx
app/front/app/routes/about.tsx
app/front/app/routes/announcements.$id.tsx
app/front/app/routes/announcements._index.tsx
app/front/app/routes/announcements.tsx
app/front/app/routes/issues.$id.tsx

Announcements page:
Announcement Details:
There are still some issues (no upvote, no emoji reactions and no rate limiting) but this pr is becoming huge so I will make a separate one

FEAT: Announcements

---

.gitignore
app/app/urls.py
app/db/models.py
app/db/views.py
app/front/app/components/NavBar.tsx
app/front/app/routes/about.tsx
app/front/app/routes/announcements.$id.tsx
app/front/app/routes/announcements._index.tsx
app/front/app/routes/announcements.tsx
app/front/app/routes/issues.$id.tsx
app/front/app/routes/issues._index.tsx

Instead of blocking users who try to vote twice, clicking a second time on the upvote button will just remove one vote

Fix: Now remove one vote instead of blocking multiple votes

---

app/front/app/routes/issues._index.tsx

Currently sorted in the frontend, but it's easier. We can change it when it becomes a problem lul.

fix(front): sort issues

---

app/front/app/routes/issues.new.tsx

refactor(front): split info block for issues/new

---

app/front/app/root.tsx
app/front/app/routes/issues.$id.tsx
app/front/app/routes/issues.new.tsx

fix(front): navbar not working for root and issues/new

---

src/app/routes/issues.$id.tsx
src/tailwind.config.ts

Add: 
* Now track the vote state of the current session to change the button color accordingly
**hasVoted == false:**
**hasVoted == true:**
Also removed these ugly ass popups

FIX: hasVoted state

---

src/app/routes/issues.$id.tsx

Currently the button is just white. Now it is a black button.

fix: issue go back button visibility

---

src/app/routes/_auth.oauth.callback.tsx
src/app/routes/admin.council-members.tsx
src/app/routes/issues.new.tsx
src/app/utils/session.server.ts
src/prisma/migrations/20240709193406_add_sessions/migration.sql
src/prisma/schema.prisma

feat: make sessions server side

---

src/app/routes/issues._index.tsx

feat: show all table cells on issue list

---

src/app/routes/issues.new.tsx

As discussed on Discord with a part of the student council.

chore(front): rephrase warning in issues

---

src/app/routes/about.tsx
src/app/routes/contact.tsx

E-Mail is the German spelling of email.

chore(front): fix English spelling of email

---

src/app/routes/issues.$id.tsx

fix: show rate limit message for too many comments

---

src/app/routes/issues.$id.tsx

feat: save comment draft in local storage

---

src/app/routes/contact.tsx

Now the cursor indicates wherever a list is clickable.

improve(front): change cursor icon over text in list

---

src/app/routes/admin.council-members.tsx
src/app/routes/contact.tsx
src/app/routes/issues.$id.tsx
src/app/routes/issues.new.tsx

- Also to success messages, like in the contact page.

chore(front): slightly increase top margin to error msgs

---

src/app/routes/issues.$id.tsx
src/app/routes/issues.new.tsx

@ifaoji Why do the bullet points not work? Is it bc it can only be strings?

fix(front): Update anonymity warnings

---

src/app/routes/contact.tsx
src/app/routes/issues.$id.tsx

**Issue detail page:**
- The upvote button was a slightly different black (it did pop more though).
- Same for the comment submit button, but it should not pop more than other buttons anyway.
- I don't know what the close button does, I have never seen it.
**Contact page:**
- The contact submit button was too bright and not fitting at all.

fix(front): make buttons consistent

---

src/app/routes/issues.$id.tsx
src/app/routes/issues._index.tsx

- Also use user's locale for issue time format instead of hardcoded en-GB.

improve(front): display date and time of issue comments

---

src/app/routes/issues.$id.tsx
src/app/routes/issues._index.tsx

Reverts 42-student-council/website#101

Revert "improve(front): display date and time of issue comments"

---

src/app/routes/contact.tsx

feat: add anonymous contact option to contact form

---

src/app/routes/issues.$id.tsx
src/app/routes/issues.new.tsx

- Change text in comment button to `Comment`.
- Improve text formatting in new issue info box.

improve(front): comment button and new issue info box

---

src/app/routes/contact.tsx

fix: contact form mobile width

---

src/app/components/ui/alert-dialog.tsx
src/app/routes/issues.$id.tsx
src/app/routes/issues._index.tsx
src/app/utils/session.server.ts
src/package-lock.json
src/package.json
src/prisma/migrations/20240719125821_feat_archive/migration.sql
src/prisma/schema.prisma

feat: archive issues

---

src/app/components/ui/alert-dialog.tsx
src/app/routes/issues.$id.tsx
src/app/routes/issues._index.tsx
src/app/utils/session.server.ts
src/package-lock.json
src/package.json
src/prisma/migrations/20240719125821_feat_archive/migration.sql
src/prisma/migrations/20240719234529_feat_official_comments/migration.sql
src/prisma/schema.prisma

feat: official answers

---

src/app/routes/issues.$id.tsx
src/tailwind.config.ts

refactor: issue styling

---

src/app/routes/issues._index.tsx

Also fix the weird, too long button on mobile by having it switch to a shorter text on smaller devices.

feat: put a policy into description of archived issues

---

src/app/routes/issues._index.tsx

feat: add right clickable link to issue titles

---

src/app/routes/issues.$id.tsx

feat: make comments upvotable

---

src/app/routes/issues._index.tsx

fix: open issue list should not be called online

---

src/app/routes/issues.$id.tsx

feat: add date of issue to issue detail page

---

src/app/routes/issues._index.tsx

- Fixes 8/10 tasks of #130.
Worked together with [@leske42](https://github.com/leske42)
---
**Issues remaining:**
- The chosen sorting should be remembered when navigating to another page and back, or when refreshing.
- Changing the sorting should apply to both the "Online" and "Archived" tab.

improve: improve sorting behavior

---

src/app/routes/issues.$id.tsx
src/app/routes/issues._index.tsx
src/app/utils/date.ts

If it was today: `Today at <time>`
If it was yesterday: `Yesterday at <time>`
Else: `<date> <time>`

refactor: show dates in a nicer way

---

src/app/routes/issues.$id.tsx
src/app/routes/issues._index.tsx

improve(front): make all pages a consistent width

---

src/app/routes/issues._index.tsx

feat: add comment count to issues list

---

src/app/routes/issues._index.tsx

Having the votes and comments next to each other looks weird.
Leo also suggested to move the votes more to the left.

improve: move votes column to the left

---

src/app/routes/issues._index.tsx

Since the design is not ideal yet:
Reverts 42-student-council/website#157

Revert "improve: move votes column to the left"

---

src/app/routes/issues.new.tsx

fix: new issue discord webhook error handling

---

src/app/routes/issues.$id.tsx

fix: fix text overflow issues

---

.env.example
.github/docs/DOTENV.md
compose.yml
src/scripts/entrypoint.sh

- Create .env.example from docs
- Clean up compose.yml
- Reference new example file in docs
- Format entrypoint.sh

refactor: environment and compose

---

src/app/routes/polls.$id.tsx
src/prisma/migrations/20241002150608_add_polls/migration.sql
src/prisma/schema.prisma

feat: polls

---

src/app/components/ui/alert.tsx
src/app/tailwind.css
src/tailwind.config.ts

So i have made new beautiful colors for dark mode & like this light mode is black again. it is approved by Lukas & Arthur. also i put the color definition for the note thing in the css file so its easier to edit if you want to change it.

added new colors for light and dark mode

---

src/app/utils/date.ts

https://github.com/user-attachments/assets/8399332d-4d12-46fb-bc65-a85120e1598b

fix: dates UTC flash

---

src/app/routes/_app.issues.$id.tsx

Restores changes made in #197 
Probably overwritten by another PR.
https://github.com/42-student-council/website/pull/197#issuecomment-2409051103

fix: use right back button in issue details

---

src/app/components/NavBar.tsx
src/app/routes/_app._index.tsx

Also link button in Home to election.
This is ofc temporary.

feat: add election tab to navbar
